### ISSUE TITLE
improvement - avoid java.nio.file.NoSuchFileException when configuring replicates with TMT data 

### ISSUE THREAD

**Issue by merbllab** [Nesvilab/TMT-Integrator#8]
Hi,
this is a suggestion for a more informative error:
when I configure replicate number with TMT data and TMT integrator is enable I get the following FragPipe crash:

12:18:06 ERROR: Error delivering events through the bus

java.lang.IllegalStateException: java.nio.file.NoSuchFileException: D:\CPTAC_Breast_Cancer_S039\02CPTAC\annotation.txt -> D:\CPTAC_Breast_Cancer_S039\analysis_2\02CPTAC\annotation.txt
	at com.dmtavt.fragpipe.cmd.CmdLabelquant.configure(CmdLabelquant.java:100)
	at com.dmtavt.fragpipe.FragpipeRun.lambda$configureTaskGraph$47(FragpipeRun.java:1053)
	at com.dmtavt.fragpipe.FragpipeRun.configureTaskGraph(FragpipeRun.java:1204)
	at com.dmtavt.fragpipe.FragpipeRun.run(FragpipeRun.java:177)
	at com.dmtavt.fragpipe.tabs.TabRun.on(TabRun.java:153)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:510)
	at org.greenrobot.eventbus.EventBus.invokeSubscriber(EventBus.java:504)
	at org.greenrobot.eventbus.AsyncPoster.run(AsyncPoster.java:46)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

Caused by: java.nio.file.NoSuchFileException: D:\CPTAC_Breast_Cancer_S039\02CPTAC\annotation.txt -> D:\CPTAC_Breast_Cancer_S039\analysis_2\02CPTAC\annotation.txt
	at sun.nio.fs.WindowsException.translateToIOException(Unknown Source)
	at sun.nio.fs.WindowsException.rethrowAsIOException(Unknown Source)
	at sun.nio.fs.WindowsFileCopy.copy(Unknown Source)
	at sun.nio.fs.WindowsFileSystemProvider.copy(Unknown Source)
	at java.nio.file.Files.copy(Unknown Source)
	at com.dmtavt.fragpipe.cmd.CmdLabelquant.configure(CmdLabelquant.java:98)
	... 14 common frames omitted

this is well documented in your tutorials but it took me some effort to understand the source of the problem. if applying replicates number to such analysis is illegal, I suggest to set it as an alarm.

thanks
Assaf

**Comment by huiyinc** [comment]
Hi Assaf,

This issues is more related to FragPipe, instead of TMT-Integrator. Have you received any response from the FragPipe repository? Or should I transfer this issue to FragPipe for you? Thanks.

Huiyin
